# Generated by Django 5.2.3 on 2025-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('indicator', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=128)),
                ('news_text', models.TextField()),
                ('analysis', models.TextField()),
                ('sentiment', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_value', models.FloatField()),
                ('cash', models.FloatField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('action', models.CharField(max_length=8)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('result', models.CharField(blank=True, max_length=16, null=True)),
                ('profit', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
