# Generated by Django 5.2.3 on 2025-07-04 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=100000.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('avg_buy_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='profit',
            new_name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='action',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='result',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='ticker',
        ),
        migrations.AddField(
            model_name='trade',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(default='TEST', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Alım'), ('SELL', 'Satım'), ('BOT', 'Bot İşlemi')], default='BUY', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
