# Generated by Django 5.2.3 on 2025-07-04 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_balance_portfolio_stock_delete_indicator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_value', models.FloatField()),
                ('total_profit', models.FloatField()),
            ],
        ),
    ]
